[build-system]
requires = ["setuptools>=42", "wheel", "pbr"]
build-backend = "setuptools.build_meta"

#[build-system]
#requires = ["poetry-core>=1.0.0","poetry-version-plugin"]
#build-backend = "poetry.core.masonry.api"

#[tool.poetry-version-plugin]
#source = "git-tag"

[tool.poetry]
name = "cypackage"
version = "0.0.1"
description = "Compile a package in one .so file and remove source code"
authors = ["liuyvjin"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/liuyvjin/cypackage"
repository = "https://github.com/liuyvjin/cypackage/"
documentation = "https://github.com/liuyvjin/cypackage/"
keywords = ["cython", "setuptools"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
packages = [
    { include = "cypackage/*.py", format = "sdist" }
]
include = ["ChangeLog", "AUTHORS"]

[tool.poetry.dependencies]
python = "^3.7"
cython = "^0.29.24"
setuptools = { version = ">=42", optional = true }
poetry-core = { version = ">=1.0.0", optional = true }

[tool.poetry.extras]
build = ["setuptools"]
poetry = ["poetry-core", "setuptools"]

[tool.poetry.dev-dependencies]
cibuildwheel = "~2"
twine = "~3"

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/liuyvjin/cypackage/issues"

# FIXME : Poetry can not generate entry_points.txt
#[tool.poetry.scripts]
#distutils.setup_keywords = "cythonpackage:cythonpackage"


